/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MatveevaliAmbulanceWlList {
    }
}
declare global {
    interface HTMLMatveevaliAmbulanceWlListElement extends Components.MatveevaliAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMatveevaliAmbulanceWlListElement: {
        prototype: HTMLMatveevaliAmbulanceWlListElement;
        new (): HTMLMatveevaliAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "matveevali-ambulance-wl-list": HTMLMatveevaliAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MatveevaliAmbulanceWlList {
    }
    interface IntrinsicElements {
        "matveevali-ambulance-wl-list": MatveevaliAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "matveevali-ambulance-wl-list": LocalJSX.MatveevaliAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMatveevaliAmbulanceWlListElement>;
        }
    }
}
